"""
YouTube thumbnail generator — bold typographic style.

Layout (1280×720):
  Left  ~45% (576px): black background + large bold hook text + red accent word
  Right ~55% (704px): AI-generated scene image (DALL-E 3) with fade edge

The hook text (2 lines white + 1 accent word in red) is generated by Claude Haiku
based on the video title and description.
The background image is generated by DALL-E 3 (falls back to AMV frame extraction).

Usage:
    python scripts/generate_thumbnail.py \
        --script-path output/run-001/script/script.json \
        --output-dir output/run-001
"""
import argparse
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

import anthropic

sys.path.insert(0, str(Path(__file__).parent.parent))
from scripts.utils.config import load_config, get_ffmpeg_path
from scripts.utils.file_helpers import ensure_dir
from scripts.utils.state_manager import StateManager

FFMPEG = get_ffmpeg_path()


def parse_args():
    parser = argparse.ArgumentParser(description="Generate YouTube thumbnail")
    parser.add_argument("--script-path", required=True, help="Path to script.json")
    parser.add_argument("--output-dir", required=True, help="Output directory for this run")
    parser.add_argument("--highlight-frame", default=None,
                        help="Path to a specific frame image/video to use as the thumbnail background")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Frame extraction
# ---------------------------------------------------------------------------

def extract_highlight_frame(frames_dir: Path, thumbnail_dir: Path) -> Path | None:
    """Extract a still frame from the most dramatic scene in frames/."""
    video_exts = {".mp4", ".webm", ".mov"}
    image_exts = {".jpg", ".jpeg", ".png"}

    if not frames_dir.exists():
        return None

    all_files = sorted(frames_dir.iterdir())
    video_files = [f for f in all_files if f.suffix.lower() in video_exts]
    image_files = [f for f in all_files if f.suffix.lower() in image_exts]

    out = thumbnail_dir / "highlight_frame.jpg"

    if video_files:
        # Pick second scene if available — often more dramatic than the intro
        pick = video_files[1] if len(video_files) > 1 else video_files[0]
        try:
            subprocess.run(
                [FFMPEG, "-y", "-i", str(pick), "-ss", "00:00:01",
                 "-vframes", "1", "-q:v", "2", str(out)],
                check=True, capture_output=True,
            )
            return out
        except Exception as e:
            print(f"  ffmpeg frame extract failed: {e}")

    if image_files:
        pick = image_files[1] if len(image_files) > 1 else image_files[0]
        try:
            from PIL import Image
            Image.open(pick).convert("RGB").save(str(out), "JPEG")
            return out
        except Exception as e:
            print(f"  Image copy failed: {e}")

    return None


# ---------------------------------------------------------------------------
# DALL-E 3 image generation
# ---------------------------------------------------------------------------

def generate_dalle_frame(script: dict, out_path: Path, config: dict) -> Path | None:
    """Generate thumbnail background image using DALL-E 3."""
    api_key = config.get("openai_api_key")
    if not api_key:
        print("  No OPENAI_API_KEY — skipping DALL-E generation")
        return None

    try:
        from openai import OpenAI

        content_type = script.get("content_type", "anime")
        scenes = script.get("scenes", [])

        # Pick a visually interesting scene (skip rank_transition and intro)
        candidates = [
            s["visual_prompt"]
            for s in scenes
            if s.get("scene_type") not in ("rank_transition", "intro")
            and s.get("visual_prompt")
        ]
        visual = candidates[len(candidates) // 2] if candidates else script.get("title", "")

        if content_type == "bedtime-story":
            style = (
                "children's storybook illustration, soft watercolor style, "
                "warm golden lighting, dreamy cozy atmosphere, gentle pastel colors, "
                "cute characters, magical mood"
            )
        else:
            style = (
                "anime cinematic art, dramatic studio lighting, ultra-detailed, "
                "vibrant saturated colors, MAPPA-style quality, epic atmosphere, "
                "dynamic heroic composition, character prominently visible"
            )

        prompt = (
            f"{visual}. {style}. "
            "Right-panel composition with strong visual focus. "
            "No text, no watermarks, no logos, no subtitles."
        )

        client = OpenAI(api_key=api_key)
        response = client.images.generate(
            model="dall-e-3",
            prompt=prompt[:4000],
            size="1792x1024",
            quality="standard",
            n=1,
        )

        url = response.data[0].url
        urllib.request.urlretrieve(url, str(out_path))
        return out_path

    except Exception as e:
        print(f"  DALL-E generation failed: {e}")
        return None


# ---------------------------------------------------------------------------
# Hook text generation
# ---------------------------------------------------------------------------

def generate_hook_text(title: str, description: str) -> tuple[list[str], str]:
    """
    Use Claude Haiku to produce 3 elements for the thumbnail:
      [line1, line2, accent_word]
    line1 + line2 are white; accent_word is red.
    Falls back to a generic hook if the API call fails.
    """
    try:
        client = anthropic.Anthropic()
        prompt = (
            "You are creating text for a YouTube anime video thumbnail in a bold typographic style.\n\n"
            f"Video title: {title}\n"
            f"Description: {description[:300]}\n\n"
            "Generate thumbnail hook text with exactly 3 elements:\n"
            "- Element 1: 1-2 words, ALL CAPS (hook setup, white text)\n"
            "- Element 2: 1-2 words, ALL CAPS (hook payoff, white text)\n"
            "- Element 3: 1 word, ALL CAPS (category/emotion, red accent)\n\n"
            "Rules:\n"
            "- Be punchy and click-worthy\n"
            "- Max 12 characters per element\n"
            "- Examples: [\"MUST\", \"WATCH\", \"ANIME\"] or [\"PURE\", \"POWER\", \"RANKING\"] "
            "or [\"DARK\", \"TRUTH\", \"REVEALED\"]\n\n"
            "Respond with ONLY a JSON array of exactly 3 strings. Nothing else."
        )
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=60,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = msg.content[0].text.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        parts = json.loads(raw.strip())
        if isinstance(parts, list) and len(parts) == 3:
            return [str(p).upper() for p in parts[:2]], str(parts[2]).upper()
    except Exception as e:
        print(f"  Hook generation failed: {e} — using fallback")

    return ["MUST", "WATCH"], "ANIME"


# ---------------------------------------------------------------------------
# PIL composition
# ---------------------------------------------------------------------------

def _find_font() -> str | None:
    import platform
    if platform.system() == "Windows":
        candidates = [
            "C:/Windows/Fonts/impact.ttf",
            "C:/Windows/Fonts/ariblk.ttf",
            "C:/Windows/Fonts/arialbd.ttf",
        ]
    else:
        candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/System/Library/Fonts/Helvetica.ttc",
        ]
    for p in candidates:
        if Path(p).exists():
            return p
    return None


def _fit_crop(img, target_w: int, target_h: int):
    from PIL import Image
    img = img.convert("RGB")
    ratio = max(target_w / img.width, target_h / img.height)
    nw = max(1, int(img.width * ratio))
    nh = max(1, int(img.height * ratio))
    img = img.resize((nw, nh), Image.LANCZOS)
    left = (nw - target_w) // 2
    # Bias upward so character faces stay visible
    top = max(0, (nh - target_h) // 4)
    return img.crop((left, top, left + target_w, top + target_h))


def _draw_outlined_text(draw, pos, text, font, fill, outline=(0, 0, 0), width=5):
    x, y = pos
    for dx in range(-width, width + 1):
        for dy in range(-width, width + 1):
            if dx or dy:
                draw.text((x + dx, y + dy), text, font=font, fill=outline)
    draw.text((x, y), text, font=font, fill=fill)


def compose_thumbnail(
    frame_path: Path | None,
    hook_lines: list[str],
    accent_word: str,
    output_path: Path,
):
    from PIL import Image, ImageDraw, ImageFont

    W, H = 1280, 720
    SPLIT = int(W * 0.44)   # 563px — text panel width
    FADE_W = 130            # gradient fade from black into the frame

    # Dark base
    canvas = Image.new("RGB", (W, H), (0, 0, 0))

    # --- Paste character frame on the right ---
    if frame_path and frame_path.exists():
        try:
            frame = _fit_crop(Image.open(frame_path), W - SPLIT, H)
            canvas.paste(frame, (SPLIT, 0))
        except Exception as e:
            print(f"  Frame paste failed: {e}")

    # --- Gradient fade at the split edge ---
    overlay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw_ov = ImageDraw.Draw(overlay)
    for x in range(SPLIT, min(SPLIT + FADE_W, W)):
        alpha = int(255 * (1 - (x - SPLIT) / FADE_W))
        draw_ov.line([(x, 0), (x, H)], fill=(0, 0, 0, alpha))
    canvas = Image.alpha_composite(canvas.convert("RGBA"), overlay).convert("RGB")

    draw = ImageDraw.Draw(canvas)
    font_path = _find_font()

    all_lines = hook_lines + [accent_word]
    n = len(all_lines)
    pad = 48
    available_w = SPLIT - pad * 2

    # Scale font size to fit the widest line inside the text panel
    font_size = 200
    f_main = f_accent = None
    if font_path:
        while font_size > 40:
            try:
                f = ImageFont.truetype(font_path, font_size)
                max_w = max(draw.textbbox((0, 0), line, font=f)[2] for line in all_lines)
                # Tight line spacing: 90% of font size
                total_h = int(font_size * 0.9) * n
                if max_w <= available_w and total_h <= H - pad * 2:
                    f_main = f
                    f_accent = f
                    break
                font_size -= 6
            except Exception:
                break

    if f_main is None:
        f_main = f_accent = ImageFont.load_default()
        font_size = 12

    line_h = int(font_size * 0.92)
    total_text_h = line_h * n
    y = (H - total_text_h) // 2

    for line in hook_lines:
        _draw_outlined_text(draw, (pad, y), line, f_main, fill=(255, 255, 255), width=5)
        y += line_h

    # Accent word in red
    _draw_outlined_text(draw, (pad, y), accent_word, f_accent, fill=(220, 25, 25), width=5)

    canvas.save(str(output_path), "JPEG", quality=92, optimize=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    config = load_config()
    script = json.loads(Path(args.script_path).read_text(encoding="utf-8"))
    output_dir = Path(args.output_dir)
    thumbnail_dir = ensure_dir(output_dir / "thumbnail")
    frames_dir = output_dir / "frames"

    state = StateManager()
    state.update_step("step-06-thumbnail-creation", "running")

    title = script.get("title", "")
    description = script.get("description", "")

    print("Getting thumbnail background image...")
    if args.highlight_frame:
        # Manual override always wins
        custom = Path(args.highlight_frame)
        if custom.suffix.lower() in (".mp4", ".webm", ".mov", ".mkv"):
            out_frame = thumbnail_dir / "highlight_frame.jpg"
            subprocess.run(
                [FFMPEG, "-y", "-i", str(custom), "-ss", "00:00:05",
                 "-vframes", "1", "-q:v", "2", str(out_frame)],
                check=True, capture_output=True,
            )
            frame_path = out_frame
        else:
            frame_path = custom
        print(f"  Frame (custom override): {frame_path}")
    else:
        # Try DALL-E 3 first
        dalle_out = thumbnail_dir / "dalle_frame.jpg"
        print("  Generating image with DALL-E 3...")
        frame_path = generate_dalle_frame(script, dalle_out, config)
        if frame_path:
            print(f"  DALL-E frame saved: {frame_path.name}")
        else:
            # Fallback: extract frame from AMV/frames directory
            print("  Falling back to AMV frame extraction...")
            frame_path = extract_highlight_frame(frames_dir, thumbnail_dir)
            if frame_path:
                print(f"  Frame (AMV extract): {frame_path}")
            else:
                print("  No frame available — text-only thumbnail")

    print("Generating hook text...")
    hook_lines, accent_word = generate_hook_text(title, description)
    print(f"  Hook: {' / '.join(hook_lines)} / {accent_word}")

    thumbnail_path = thumbnail_dir / "thumbnail.jpg"
    print("Composing thumbnail...")
    try:
        compose_thumbnail(frame_path, hook_lines, accent_word, thumbnail_path)
    except ImportError:
        print("ERROR: Pillow not installed — run: pip install Pillow")
        state.update_step("step-06-thumbnail-creation", "failed")
        sys.exit(1)

    size_kb = thumbnail_path.stat().st_size // 1024
    print(f"  Saved: {thumbnail_path} ({size_kb} KB)")
    state.update_step(
        "step-06-thumbnail-creation", "completed",
        {"thumbnail_path": str(thumbnail_path), "hook": hook_lines + [accent_word]},
    )


if __name__ == "__main__":
    main()
